FROM tensorflow/tensorflow:latest-gpu
ENV XLA_FLAGS=--xla_gpu_cuda_data_dir=/usr/local/cuda-11.8
RUN mkdir /gendock
WORKDIR /gendock
COPY ./requirements.txt /gendock/requirements.txt
RUN apt-get update
RUN pip --timeout=1000 install --no-cache-dir --upgrade -r /gendock/requirements.txt
RUN pip install celery[redis]
RUN pip install psycopg2-binary
RUN apt-get install -y openbabel
COPY . /gendock/
RUN chmod +x ./entrypoint.sh
ENTRYPOINT [ "/gendock/entrypoint.sh" ]