# Generated by Django 4.2.4 on 2023-08-19 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedcsv',
            name='cleaned_smiles_file',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
