# Generated by Django 4.2.4 on 2023-08-20 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0002_uploadedcsv_cleaned_smiles_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedcsv',
            name='task_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
