# Generated by Django 4.2.4 on 2023-08-23 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0003_uploadedcsv_task_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleanSmiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cleaned_smile_path', models.CharField(max_length=100)),
                ('csv_files', models.CharField(max_length=200)),
            ],
        ),
    ]
