# Generated by Django 4.2.4 on 2023-08-25 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0007_cleanedsmile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedcsv',
            name='task_id',
        ),
        migrations.AddField(
            model_name='cleanedsmile',
            name='task_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
