# Generated by Django 4.2.4 on 2023-08-27 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0008_remove_uploadedcsv_task_id_cleanedsmile_task_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedcsv',
            name='cleaned_smiles_file',
        ),
        migrations.AlterField(
            model_name='cleanedsmile',
            name='cleaned_file',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='cleanedsmile',
            name='csv_file',
        ),
        migrations.AddField(
            model_name='cleanedsmile',
            name='csv_file',
            field=models.ManyToManyField(to='gui.uploadedcsv'),
        ),
    ]
