# Generated by Django 4.2.4 on 2023-08-27 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0009_remove_uploadedcsv_cleaned_smiles_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleanedsmile',
            name='task_status',
            field=models.CharField(choices=[('P', 'Processing'), ('C', 'Completed'), ('F', 'Failed'), ('N', 'Not Started')], default='N', max_length=1),
        ),
    ]
