# Generated by Django 4.2.4 on 2023-09-04 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0010_cleanedsmile_task_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=50, unique=True)),
                ('epoch', models.IntegerField()),
                ('train_loss', models.CharField(max_length=20)),
                ('val_loss', models.CharField(max_length=20)),
                ('task_status', models.CharField(choices=[('P', 'Processing'), ('C', 'Completed'), ('F', 'Failed'), ('N', 'Not Started')], default='N', max_length=1)),
            ],
        ),
    ]
