# Generated by Django 4.2.4 on 2023-09-04 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0011_trainlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainlog',
            name='epoch',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='trainlog',
            name='train_loss',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='trainlog',
            name='val_loss',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
