# Generated by Django 4.2.4 on 2023-09-04 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0012_alter_trainlog_epoch_alter_trainlog_train_loss_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainlog',
            name='max_epoch',
            field=models.IntegerField(null=True),
        ),
    ]
