# Generated by Django 4.2.4 on 2023-09-04 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0013_trainlog_max_epoch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainlog',
            name='epoch',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
