# Generated by Django 4.2.4 on 2023-09-05 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0015_alter_trainlog_epoch'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainlog',
            name='cur_batch',
            field=models.IntegerField(default=0),
        ),
    ]
