# Generated by Django 4.2.4 on 2023-09-06 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0016_trainlog_cur_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainlog',
            name='max_batch',
            field=models.IntegerField(default=0),
        ),
    ]
