# Generated by Django 4.2.4 on 2023-09-06 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0017_trainlog_max_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainlog',
            name='max_batch',
            field=models.IntegerField(default=1),
        ),
    ]
