# Generated by Django 4.2.4 on 2023-09-09 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0019_receptorconfiguration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receptorconfiguration',
            name='receptor_file',
        ),
    ]
