# Generated by Django 4.2.4 on 2023-09-18 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0023_alter_receptorconfiguration_receptor_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receptorconfiguration',
            name='receptor_file',
            field=models.FileField(upload_to='receptor_files/'),
        ),
    ]
