# Generated by Django 4.2.4 on 2023-09-19 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0024_alter_receptorconfiguration_receptor_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receptorconfiguration',
            name='size_x',
            field=models.DecimalField(decimal_places=2, default=30, max_digits=10),
        ),
        migrations.AlterField(
            model_name='receptorconfiguration',
            name='size_y',
            field=models.DecimalField(decimal_places=2, default=30, max_digits=10),
        ),
        migrations.AlterField(
            model_name='receptorconfiguration',
            name='size_z',
            field=models.DecimalField(decimal_places=2, default=30, max_digits=10),
        ),
    ]
