# Generated by Django 4.2.4 on 2023-09-20 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0025_alter_receptorconfiguration_size_x_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receptorconfiguration',
            name='center_x',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='receptorconfiguration',
            name='center_y',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='receptorconfiguration',
            name='center_z',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='receptorconfiguration',
            name='size_x',
            field=models.DecimalField(decimal_places=5, default=30, max_digits=10),
        ),
        migrations.AlterField(
            model_name='receptorconfiguration',
            name='size_y',
            field=models.DecimalField(decimal_places=5, default=30, max_digits=10),
        ),
        migrations.AlterField(
            model_name='receptorconfiguration',
            name='size_z',
            field=models.DecimalField(decimal_places=5, default=30, max_digits=10),
        ),
    ]
